# Generated by Django 2.2.2 on 2019-12-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos de Oferente')),
                ('turno', models.CharField(max_length=200, verbose_name='Apellidos de Oferente')),
                ('dia', models.CharField(max_length=200, verbose_name='Dia de Oferente')),
                ('pago', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('colonia', models.CharField(max_length=200, verbose_name='Colonia de Oferente')),
                ('superficie', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('estadoDiscapacidad', models.BooleanField(default=False, verbose_name='Si/ No ')),
                ('estadoAM', models.BooleanField(default=False, verbose_name='Si/ No ')),
                ('estadoTirado', models.BooleanField(default=False, verbose_name='Si/ No ')),
                ('nombres', models.CharField(max_length=200, verbose_name='Giro de Oferente')),
                ('tipoPermiso', models.CharField(max_length=200, verbose_name='Mercado Correspondiente')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Oferente',
                'verbose_name_plural': 'Oferentes',
            },
        ),
    ]
