# Generated by Django 2.2.2 on 2019-12-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavacitos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Inspector')),
                ('contrasena', models.CharField(max_length=100, verbose_name='Contraseña Inspector')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Inspector',
                'verbose_name_plural': 'Inspectores',
            },
        ),
        migrations.AlterField(
            model_name='oferente',
            name='estadoAM',
            field=models.BooleanField(default=False, verbose_name='Si Adulto Mayor/ No Adulto Mayor '),
        ),
        migrations.AlterField(
            model_name='oferente',
            name='estadoDiscapacidad',
            field=models.BooleanField(default=False, verbose_name='Con Discapacidad/ Sin Discapacidad '),
        ),
        migrations.AlterField(
            model_name='oferente',
            name='estadoTirado',
            field=models.BooleanField(default=False, verbose_name='Si Tirado/ No Tirado '),
        ),
        migrations.AlterField(
            model_name='oferente',
            name='turno',
            field=models.CharField(max_length=200, verbose_name='Turno del Oferente'),
        ),
    ]
