# Generated by Django 2.2.2 on 2019-12-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavacitos', '0002_auto_20191207_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferente',
            name='nombre',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombres de Oferente'),
        ),
    ]
